services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: escola_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha_mestra
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: qt_login_app
    environment:
      - DISPLAY=host.docker.internal:0
    depends_on:
      - db